YOMA_NAME="Minimal"

YOMA_BANNER='
YOMA • TERMUX
'

YOMA_PROMPT='PS1="\[\e[1;37m\]\w \[\e[1;31m\]❯ \[\e[0m\]"'

YOMA_COLORS='background=#101010
foreground=#eeeeee
cursor=#ffffff
color0=#101010
color1=#d14
color2=#5a5
color3=#aa5
color4=#58f
color5=#a5a
color6=#5aa
color7=#aaa
color8=#555
color9=#f55
color10=#5f5
color11=#ff5
color12=#5af
color13=#f5f
color14=#5ff
color15=#fff'
